<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }} - Print Export</title>
    <style>
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; color: #111827; padding: 40px; line-height: 1.5; }
        .header { margin-bottom: 40px; border-bottom: 2px solid #f3f4f6; padding-bottom: 20px; }
        .header h1 { margin: 0; font-size: 24px; font-weight: 800; color: #4f46e5; }
        .header p { margin: 5px 0 0; color: #6b7280; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 600; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
        th { background: #f9fafb; border-bottom: 1px solid #e5e7eb; padding: 12px 15px; text-align: left; color: #4b5563; font-weight: 700; text-transform: uppercase; }
        td { border-bottom: 1px solid #f3f4f6; padding: 10px 15px; color: #374151; }
        tr:nth-child(even) { background: #fafafa; }
        
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
            table { page-break-inside: auto; }
            tr { page-break-inside: avoid; page-break-after: auto; }
        }
        
        .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Exported Data Report • {{ now()->format('d M Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th>{{ $col['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    @foreach($columns as $col)
                        <td>
                            @php
                                $val = $row->{$col['key']};
                            @endphp
                            {{ is_array($val) ? json_encode($val) : $val }}
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by KreatifCMS Advanced DataGrid
    </div>

    <script>
        window.onload = () => {
            window.print();
        };
    </script>
</body>
</html>
